'use strict';
// Source and model text only enters textContent; never HTML markup.
const $ = id => document.getElementById(id);
const node = (tag, text, cls) => {const e=document.createElement(tag); if(text!==undefined)e.textContent=text; if(cls)e.className=cls; return e;};
let snapshot, selected, signature, sequence=0, allEvents=[];
const fmt = x => x === null || x === undefined ? 'unknown' : Number(x).toLocaleString(undefined,{maximumFractionDigits:2});
const duration = x => x === null || x === undefined ? 'unknown' : `${Math.floor(x/60)}m ${Math.floor(x%60)}s`;
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function json(parent,value){parent.append(node('pre',JSON.stringify(value,null,2)));}
function artifact(parent,kind,id){if(!id)return;const path=`${kind}/${id}.json`;const b=node('button',`Open ${path}`);b.onclick=async()=>{try{const r=await fetch(`/api/artifact/${kind}/${id}`,{signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('Unavailable artifact');const data=await r.json();const pre=node('pre',JSON.stringify(data,null,2));const d=node('button','Download record JSON');d.onclick=()=>download(data,`${id}.json`);b.after(pre,d);if(kind==='evidence'&&data.document_id)artifact(parent,'documents',data.document_id);b.disabled=true;}catch(e){b.after(node('p',String(e)));}};parent.append(b);}
function section(parent,title,value){const d=node('details');d.append(node('summary',title));json(d,value);parent.append(d);return d;}
function inspect(task){const panel=$('inspector'),oldScroll=panel.scrollTop;const openDetails=new Set([...panel.querySelectorAll('details[open]')].map(d=>d.firstChild.textContent));panel.replaceChildren(node('h2',`${task.role} · ${task.task_id}`));
 const save=node('button','Download selected task JSON');save.onclick=()=>download(task,`${task.task_id}.json`);panel.append(save);
 panel.append(node('p',task.question),node('p',`${task.symbols.join(', ')} · ${task.stage} · ${task.status} · ${duration(task.duration_seconds)}${task.timing_uncertain?' (uncertain)':''}`));
 section(panel,'Brief / identity / timing / allowance',{prompt_version:task.prompt_version,model:task.model,permitted_tools:task.permitted_tools,parent:task.parent_task_id,question_id:task.question_id,horizon_sessions:task.horizon_sessions,created_at:task.created_at,started_at:task.started_at,completed_at:task.completed_at||'unknown',model_turn_limit:task.model_turn_limit,turns_remaining:task.turns_remaining});
 const findings=node('details');findings.append(node('summary','Accepted individual findings'));findings.open=true;panel.append(findings);
 const result=task.result;
 if(!result)findings.append(node('p','No accepted result yet'));
 else{
  findings.append(node('p',result.summary));
  if(result.assessment)findings.append(node('p',`Assessment: ${result.assessment}`));
  if(result.counter_thesis)findings.append(node('h3','Counter-case'),node('p',result.counter_thesis));
  const conditions=(parent,rows)=>{for(const c of rows||[]){parent.append(node('p',c.kind==='human_review'?`Human review: ${c.description}`:`Completed-close review: ${c.symbol} ${c.operator} ${c.threshold_decimal} (${c.price_basis}); expires ${c.expires_at}. ${c.description} — not an executable order.`));for(const id of c.evidence_ids||[])artifact(parent,'evidence',id);}};
  for(const row of result.instruments||[]){const d=node('details');d.append(node('summary',`${row.symbol} · ${row.assessment}`),node('p',row.thesis),node('p','Counter-case: '+row.counter_thesis),node('p','Valuation: '+row.valuation));conditions(d,row.review_conditions);findings.append(d);}
  if(result.claims?.length){findings.append(node('h3','Claims'));for(const c of result.claims){findings.append(node('p',`${c.classification}: ${c.text}`));}}
  if(result.gaps?.length){findings.append(node('h3','Evidence gaps'));for(const g of result.gaps)findings.append(node('p',`${g.critical?'Critical: ':''}${g.description}`));}
  conditions(findings,result.review_conditions);
  section(findings,'Raw accepted findings JSON',result);
 }
 const evidence=section(panel,'Visible evidence & calculations',{manifest_id:task.accepted_manifest_id||task.manifest_id,evidence_ids:task.visible_evidence_ids||[]});artifact(evidence,'manifests',task.accepted_manifest_id||task.manifest_id);for(const id of task.visible_evidence_ids||[])artifact(evidence,'evidence',id);
 const trace=node('details');trace.append(node('summary','Recorded request/tool/output trace'));trace.append(node('p','Saved inputs, outputs and tools; private model reasoning is not available. Request evidence_aliases resolves short references using that request’s frozen map.'));
 for(const [i,a] of task.attempts.entries()){const d=section(trace,`${a.attempt_id} · ${a.status}`,{...a,tool_result:task.history[i]||'No accepted tool result'});artifact(d,'requests',a.request_id);artifact(d,'responses',a.response_id);}panel.append(trace);
 section(panel,'Usage receipts',task.attempts.map(a=>({attempt_id:a.attempt_id,receipt:a.receipt||'unknown'})));
 section(panel,'Questions & dependencies',snapshot.questions.filter(q=>q.parent_task_id===task.task_id||q.answer_task_id===task.task_id));for(const d of panel.querySelectorAll('details'))if(openDetails.has(d.firstChild.textContent))d.open=true;panel.scrollTop=oldScroll;
}
function choose(id){selected=id;signature=null;render();}
function filters(){for(const [id,key] of [['role','role'],['symbol','symbols'],['stage','stage'],['filterStatus','status']]){const select=$(id),value=select.value;const vals=[...new Set(snapshot.tasks.flatMap(t=>t[key]))].sort();if(select.dataset.values===JSON.stringify(vals))continue;select.dataset.values=JSON.stringify(vals);select.replaceChildren(node('option',`All ${id==='filterStatus'?'statuses':id+'s'}`));select.firstChild.value='';for(const v of vals){const o=node('option',v);o.value=v;select.append(o);}select.value=value;}}
function render(){const s=snapshot;if(!s)return;filters();$('status').textContent=`${s.run_id} · ${s.phase} / ${s.status} · Updated ${s.updated_at||'unknown (historical telemetry)'}${s.stale?' · STALE: work beyond last observation is uncertain':''}`;
 const budget=$('budgets');budget.replaceChildren();budget.append(node('div',`Wall ${duration(s.elapsed_seconds)} / ${duration(s.limits.wall_seconds)} ceiling / ${duration(s.wall_remaining_seconds)} left`,'metric'));
 for(const k of ['model_calls','input_tokens','output_tokens','catalog_cost_usd','source_requests'])budget.append(node('div',`${k==='catalog_cost_usd'?'Catalog estimate ($)':k}: ${s.usage_unknown?'known lower bound ':''}${fmt(s.usage[k])} / ${fmt(s.limits[k])}${s.usage_unknown?' · unknown total':''}`,'metric'+(s.usage_unknown?' unknown':'')));
 budget.append(node('div',`Final reserves: ${JSON.stringify(s.reservations)} · receipts ${s.receipts_reconcile?'reconcile':'MISMATCH'}`,'metric'));
 const active=s.tasks.flatMap(t=>t.attempts).filter(a=>a.status==='STARTED');for(const a of active)budget.append(node('div',`${a.attempt_id}: worker deadline ${a.worker_deadline_at||'unknown'} · ${a.worker_deadline_at?duration(Math.max(0,(Date.parse(a.worker_deadline_at)-Date.now())/1000)):'unknown'} left${s.stale?' (last observation uncertain)':''}`,'metric'));
 const start=Date.parse(s.started_at),end=Date.parse(s.view_at||s.completed_at||s.started_at);const span=Math.max(1,(end-start)/1000,...active.map(a=>(Date.parse(a.worker_deadline_at)-start)/1000).filter(Number.isFinite));
 const pct=date=>Math.max(0,Math.min(100,(Date.parse(date)-start)/1000/span*100));$('axis').replaceChildren(node('span','0m'),node('span',duration(span/2)),node('span',duration(span)));
 const timeline=$('timeline'),table=$('table');const focus=document.activeElement?.dataset?.task,where=document.activeElement?.dataset?.surface;timeline.replaceChildren();table.replaceChildren();
 const rows=s.tasks.filter(t=>(!$('role').value||t.role===$('role').value)&&(!$('symbol').value||t.symbols.includes($('symbol').value))&&(!$('stage').value||t.stage===$('stage').value)&&(!$('filterStatus').value||t.status===$('filterStatus').value));const order=['challenger','director','company','macro','technical','geopolitics','commodities'];rows.sort((a,b)=>order.indexOf(a.role)-order.indexOf(b.role));
 for(const t of rows){const row=node('div',undefined,'row'+(selected===t.task_id?' selected':''));const button=node('button',`${t.role} · ${t.task_id} · ${t.status}${t.timing_uncertain?' (uncertain)':''}`);button.dataset.task=t.task_id;button.dataset.surface='chart';button.onclick=()=>choose(t.task_id);const track=node('div',undefined,'track');
 const part=(cls,a,b)=>{const e=node('span',undefined,cls);e.style.left=`${pct(a)}%`;e.style.width=`${Math.max(.15,pct(b)-pct(a))}%`;track.append(e);};if(t.created_at){const spawn=node('span','●','spawn');spawn.style.left=`${pct(t.created_at)}%`;track.append(spawn);part('queue',t.created_at,t.started_at||s.view_at||t.created_at);}if(t.started_at){const finish=t.completed_at||(t.status==='RUNNING'?s.view_at:t.started_at);part('bar '+(t.status==='RUNNING'?'running':t.status==='COMPLETE'?'':'failed'),t.started_at,finish);const attempt=t.attempts.find(a=>a.status==='STARTED');if(attempt?.worker_deadline_at)part('allowance',finish,attempt.worker_deadline_at);}row.append(button,track);timeline.append(row);
 const tr=node('tr');const td=node('td');const tb=node('button',`${t.task_id} / ${t.role}`);tb.dataset.task=t.task_id;tb.dataset.surface='table';tb.onclick=()=>choose(t.task_id);td.append(tb);tr.append(td);for(const v of [`${t.stage} / ${t.symbols.join(', ')}`,t.status,t.started_at||'unknown',t.completed_at||'unknown',duration(t.duration_seconds),t.turns_remaining])tr.append(node('td',String(v)));table.append(tr);}
 drawLinks(timeline,rows,s.edges.filter(e=>$('allEdges').checked||e.from===selected||e.to===selected));
 if(focus){[...document.querySelectorAll('button[data-task]')].find(b=>b.dataset.task===focus&&b.dataset.surface===where)?.focus({preventScroll:true});}
 $('omissions').replaceChildren(...s.omissions.map(o=>node('p',`${o.role}: omitted — ${o.reason}`,'omitted')),...s.planned_stages.map(p=>node('p',`${p}: planned, not spawned`,'omitted')));
 const edges=$('edges');edges.replaceChildren(node('h2','Dependency links'));for(const edge of s.edges.filter(e=>$('allEdges').checked||e.from===selected||e.to===selected)){const b=node('button',`${edge.from} → ${edge.to} · ${edge.kind}${edge.question_id?' / '+edge.question_id:''}`,'edge');b.onclick=()=>choose(edge.to);edges.append(b);}
 for(const q of s.questions.filter(q=>['PROPOSED','ACCEPTED'].includes(q.status)))edges.append(node('p',`${q.question_id}: ${q.disposition} · age ${q.created_at?duration((end-Date.parse(q.created_at))/1000):'unknown'} · no implied occupied slot`,'badge'));
 const task=s.tasks.find(t=>t.task_id===selected);if(task){const sig=JSON.stringify({...task,duration_seconds:null});if(sig!==signature){inspect(task);signature=sig;}}
}
function drawLinks(timeline,rows,edges){
 const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.classList.add('links');svg.setAttribute('aria-label','Task dependency graph');const bounds=timeline.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${bounds.width} ${bounds.height}`);
 for(const e of edges){const a=rows.findIndex(t=>t.task_id===e.from),b=rows.findIndex(t=>t.task_id===e.to);if(a<0||b<0)continue;const from=timeline.children[a].querySelector('.bar,.spawn'),to=timeline.children[b].querySelector('.spawn,.bar');if(!from||!to)continue;const ar=from.getBoundingClientRect(),br=to.getBoundingClientRect();const x1=ar.right-bounds.left,y1=ar.top-bounds.top+8,x2=br.left-bounds.left,y2=br.top-bounds.top+8;
 const path=document.createElementNS(ns,'path');path.setAttribute('d',`M${x1},${y1} C${Math.max(x1,x2)+35},${y1} ${Math.max(x1,x2)+35},${y2} ${x2},${y2}`);path.setAttribute('class',e.kind==='reused answer'?'reuse':'dependency');path.setAttribute('tabindex','0');path.setAttribute('role','button');path.setAttribute('aria-label',`${e.from} to ${e.to}: ${e.kind}`);path.onclick=()=>choose(e.to);path.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();choose(e.to);}};const title=document.createElementNS(ns,'title');title.textContent=`${e.kind}: ${e.from} → ${e.to}`;path.append(title);svg.append(path);
 }timeline.append(svg);
}
async function poll(){try{const r=await fetch(`/api/snapshot?after=${sequence}`,{signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error(`HTTP ${r.status}`);snapshot=await r.json();if(sequence===0)allEvents=snapshot.events;else allEvents.push(...snapshot.events);sequence=snapshot.sequence||0;$('events').textContent=JSON.stringify(allEvents,null,2);render();}catch(e){$('status').textContent=`Disconnected · last successful update ${snapshot?.updated_at||'unknown'} · ${e}`;}}
for(const id of ['role','symbol','stage','filterStatus','allEdges'])$(id).onchange=render;$('download').onclick=()=>snapshot&&download({...snapshot,events:allEvents},`${snapshot.run_id}.json`);$('follow').onchange=()=>{$('follow').checked&&poll();};poll();setInterval(()=>{$('follow').checked&&poll();},1000);
