'use strict';
const $=id=>document.getElementById(id), el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const params=new URLSearchParams(location.search), selected=params.get('run');
let workspace, submitting=false, requestId=crypto.randomUUID(), pendingQuestion=null, previousReport=null;
const label=s=>(s||'unknown').replaceAll('_',' '), date=s=>s?new Date(s).toLocaleString():'not recorded';
function link(text,url,cls){const a=el('a',text,cls);a.href=url;return a;}
function badge(status){return el('span',label(status),'badge '+(status==='PUBLISHED'?'':'draft'));}
async function get(url){const r=await fetch(url,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error((await r.json()).error||`HTTP ${r.status}`);return r.json();}
async function post(url,value){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Research-Token':workspace.token},body:JSON.stringify(value),signal:AbortSignal.timeout(10000)});const data=await r.json();if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);return data;}
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=link('',url);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function disclosure(parent,title,value){const d=el('details');d.append(el('summary',title),el('pre',JSON.stringify(value,null,2)));parent.append(d);return d;}
function jobCard(job){const c=el('article',undefined,'job'),body=el('div'),actions=el('div',undefined,'actions');body.append(badge(job.status),el('h2',job.question),el('p',`${date(job.created_at)} · ${job.scope.join(' / ')} · 63 sessions`));if(job.usage)body.append(el('p',`${job.usage.model_calls} model calls · $${Number(job.usage.catalog_cost_usd).toFixed(2)} catalog estimate${job.usage_unknown?' · total usage unknown':''}`));if(job.error)body.append(el('p',job.error));actions.append(link('Conclusions',`/reports?run=${job.id}`,'button secondary'),link('Monitor',`/monitor?run=${job.id}`,'button secondary'));c.append(body,actions);return c;}
function list(parent,jobs){parent.replaceChildren(...jobs.map(jobCard));if(!jobs.length)parent.append(el('p','Your saved research will appear here. Start with the pilot question above.','empty'));}
function textSection(parent,title,text){parent.append(el('h3',title),el('p',text||'Not provided in the saved assessment.'));}
function conditions(parent,rows){if(!rows?.length){parent.append(el('p','No review conditions were recorded.'));return;}for(const row of rows){const d=el('div',undefined,'condition');d.append(el('p',row.description));if(row.kind==='human_review')d.append(el('small','Requires human review'));else d.append(el('small',`${row.symbol} ${row.operator} ${row.threshold_decimal} · ${row.price_basis} · expires ${date(row.expires_at)} · completed-close review, not an executable order`));parent.append(d);}}
async function showReport(){const data=await get(`/api/runs/${selected}/report`);const signature=JSON.stringify(data);if(signature===previousReport)return;previousReport=signature;const {job,product,publication}=data;
 const header=$('reportHeader');header.replaceChildren(badge(job.status),el('h1',job.question),el('p',`${job.scope.join(' · ')} / 63 trading sessions · Started ${date(job.created_at)}${publication?' · Published '+date(publication.published_at):''}`));
 const actions=$('reportActions');actions.replaceChildren(link('Open run monitor',`/monitor?run=${job.id}`,'button secondary'));const save=el('button','Download report JSON','secondary');save.onclick=()=>download(data,`${job.id}-report.json`);actions.append(save);
 const overview=$('conclusion');overview.replaceChildren();$('instruments').replaceChildren();$('supporting').replaceChildren();
 if(job.error)overview.append(el('p',job.error,'empty'));
 if(!product){overview.append(el('p',job.busy?'Research is in progress. Accepted specialist findings are available in the monitor; final conclusions will appear here.':`No final report is available. Saved status: ${job.status}. Inspect the monitor for partial findings and the stop reason.`,'empty'));return;}
 if(!publication){const note=el('div',undefined,'overview');note.append(el('h2','Draft conclusions'),el('p','These findings have not received the final price and event refresh. Review the evidence and limitations before publication.'));overview.append(note);
   if(job.status==='DRAFT'&&!job.publication_attempted&&!job.busy){const b=el('button','Reviewed — refresh & publish');b.onclick=async()=>{b.disabled=true;try{await post(`/api/runs/${job.id}/publish`,{reviewed:true});$('notice').textContent='Publication refresh started. Material changes may withdraw affected conclusions.';previousReport=null;}catch(e){$('notice').textContent=String(e);b.disabled=false;}};actions.append(b);}}
 else{const note=el('div',undefined,'overview');note.append(el('h2','Published research'),el('p',`Immutable publication ${publication.publication_id}. Evidence cutoff: ${date(product.evidence_cutoff)}.`),el('p',`Price freshness: ${product.price_freshness?.status||'see freshness record'}. Executable quote: ${product.quote_freshness?.status||'unavailable'}.`));overview.append(note);}
 const summary=el('div',undefined,'overview');summary.append(el('h2','Overall assessment'),el('p',product.findings.summary));overview.append(summary);
 for(const row of product.findings.instruments||[]){const card=el('article',undefined,'instrument');card.append(el('h2',row.symbol),badge(row.assessment));textSection(card,'Thesis & demand drivers',row.thesis);textSection(card,'Valuation assumptions',row.valuation);textSection(card,'Downside & counter-case',row.counter_thesis);card.append(el('h3','What would change this assessment'));conditions(card,row.review_conditions);const claims=(product.findings.claims||[]).filter(c=>(row.claim_ids||[]).includes(c.claim_id));const detail=el('details');detail.append(el('summary',`Supporting claims (${claims.length})`));for(const claim of claims){detail.append(el('p',`${label(claim.classification)}: ${claim.text}`));for(const id of claim.evidence_ids||[])detail.append(link(`Evidence ${id.slice(0,10)} ↗`,`/api/runs/${job.id}/artifact/evidence/${id}`),el('br'));}card.append(detail);$('instruments').append(card);}
 const support=$('supporting');for(const key of ['gaps','shared_exposures','question_effects','objection_dispositions','role_coverage'])if(product.findings[key]?.length)disclosure(support,label(key),product.findings[key]);
 const limitations=el('section');limitations.append(el('h2','Limitations'));const ul=el('ul');for(const text of product.limitations||[])ul.append(el('li',text));limitations.append(ul);support.append(limitations);
 const sources=el('details');sources.append(el('summary',`Evidence & source dates (${data.sources.length})`));for(const source of data.sources){const row=el('div',undefined,'source');row.append(link(source.title||source.source_id||source.evidence_id,`/api/runs/${job.id}/artifact/evidence/${source.evidence_id}`));if(source.url&&/^https:\/\//.test(source.url)){const a=link(' · Original source ↗',source.url);a.target='_blank';a.rel='noopener noreferrer';row.append(a);}row.append(el('small',`Observed: ${source.data?.price_date||source.data?.as_of||source.published_at||'not recorded'} · Retrieved: ${date(source.retrieved_at)}`));sources.append(row);}support.append(sources);if(publication)disclosure(support,'Publication refresh, conditions & freshness',{refresh:publication.refresh,price_freshness:product.price_freshness,quote_freshness:product.quote_freshness});
}
async function refresh(){try{workspace=await get('/api/workspace');if(selected){await showReport();}else{list($('recent'),workspace.jobs.slice(0,3));list($('library'),workspace.jobs);$('start').disabled=submitting||workspace.jobs.some(j=>j.busy);}}catch(e){$('notice').textContent=`Connection or saved-record error: ${e}. Previously displayed results may be outdated.`;}}
$('researchForm').onsubmit=async event=>{event.preventDefault();if(submitting)return;submitting=true;$('start').disabled=true;const question=$('question').value.trim();if(pendingQuestion!==null&&pendingQuestion!==question)requestId=crypto.randomUUID();pendingQuestion=question;try{const job=await post('/api/runs',{id:requestId,question});location.href=`/reports?run=${job.id}`;}catch(e){$('notice').textContent=`${e}. The same unchanged submission keeps its request ID, so retrying does not duplicate a run.`;submitting=false;$('start').disabled=false;}};
(async()=>{try{workspace=await get('/api/workspace');$('question').value=workspace.question;const b=workspace.budgets;$('budget').textContent=`Up to ${b.model_calls} calls · ${Math.round(b.wall_seconds/60)} minutes · $${b.catalog_cost_usd} catalog estimate ceiling`;$('model').textContent=`Model: ${workspace.model}`;const library=location.pathname==='/reports';$(selected?'detail':library?'reports':'entry').hidden=false;$(library?'reportsNav':'newNav').setAttribute('aria-current','page');await refresh();setInterval(refresh,3000);}catch(e){$('notice').textContent=String(e);}})();
