'use strict';
const $=id=>document.getElementById(id), el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const params=new URLSearchParams(location.search), selected=params.get('run');
let workspace, submitting=false, requestId=crypto.randomUUID(), pendingQuestion=null, previousReport=null;
const label=s=>(s||'unknown').replaceAll('_',' '), date=s=>s?new Date(s).toLocaleString(undefined,{timeZoneName:'short'}):'not recorded';
function link(text,url,cls){const a=el('a',text,cls);a.href=url;return a;}
function badge(status){return el('span',label(status),'badge '+(status==='PUBLISHED'?'':'draft'));}
async function get(url){const r=await fetch(url,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error((await r.json()).error||`HTTP ${r.status}`);return r.json();}
async function post(url,value){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Research-Token':workspace.token},body:JSON.stringify(value),signal:AbortSignal.timeout(10000)});const data=await r.json();if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);return data;}
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=link('',url);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function disclosure(parent,title,value){const d=el('details');d.append(el('summary',title),el('pre',JSON.stringify(value,null,2)));parent.append(d);return d;}
function jobCard(job){const c=el('article',undefined,'job'),body=el('div'),actions=el('div',undefined,'actions');body.append(badge(job.status),el('h2',job.question),el('p',`${date(job.created_at)} · ${job.scope.join(' / ')} · ${(job.horizon_sessions||[63]).join(' / ')} sessions`));if(job.usage)body.append(el('p',`${job.usage.model_calls} model calls · $${Number(job.usage.catalog_cost_usd).toFixed(2)} catalog estimate${job.usage_unknown?' · total usage unknown':''}`));if(job.error)body.append(el('p',job.error));actions.append(link('Conclusions',`/reports?run=${job.id}`,'button secondary'),link('Monitor',`/monitor?run=${job.id}`,'button secondary'));c.append(body,actions);return c;}
function list(parent,jobs){parent.replaceChildren(...jobs.map(jobCard));if(!jobs.length)parent.append(el('p','Your saved research will appear here. Select stocks and a question to start.','empty'));}
function textSection(parent,title,text){parent.append(el('h3',title),el('p',text||'Not provided in the saved assessment.'));}
function conditions(parent,rows){if(!rows?.length){parent.append(el('p','No review conditions were recorded.'));return;}for(const row of rows){const d=el('div',undefined,'condition');d.append(el('p',row.description));if(row.kind==='human_review')d.append(el('small','Requires human review'));else d.append(el('small',`${row.symbol} ${row.operator} ${row.threshold_decimal} · ${row.price_basis} · expires ${date(row.expires_at)} · completed-close review, not an executable order`));parent.append(d);}}
function readinessTable(parent,readiness){
 if(!readiness)return;const section=el('details');section.append(el('summary','Source readiness — '+label(readiness.status)),el('p',readiness.qualification));for(const row of readiness.requirements){const item=el('div',undefined,'source');item.append(el('strong',`${row.symbols.join(' / ')} · ${label(row.requirement_id)} — ${label(row.status)}`),el('p',row.explanation),el('small',`Supports: ${row.dimensions.map(label).join(', ')} · Observed: ${row.observed_dates.join(', ')||'unknown'}`));section.append(item);}parent.append(section);
}
function dimensionSections(parent,dimensions){
 for(const [name,value] of Object.entries(dimensions)){const section=el('section',undefined,'dimension');section.append(el('h3',label(name)),badge(value.status),el('p',value.conclusion),el('small',value.qualification));if(value.depends_on.length)section.append(el('small','Depends on: '+value.depends_on.map(label).join(', ')));parent.append(section);}
}
function scenarioTable(parent,grid){
 parent.append(el('h3','Conditional valuation scenarios'),el('p',`Assumed annual earnings: ${grid.earnings_period_start} to ${grid.earnings_period_end} · ${grid.accounting_basis} · ${grid.share_basis}. Reference close: ${grid.observed_close_decimal} on ${grid.price_date}.`));
 const table=el('table'),head=el('tr');for(const text of ['Case','Assumed EPS','Assumed P/E','Scenario price','Change (%)'])head.append(el('th',text));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');for(const row of grid.cases){const tr=el('tr');for(const key of ['case','earnings_per_share','pe_multiple','scenario_price_decimal','change_from_close_pct_decimal'])tr.append(el('td',row[key]));body.append(tr);}table.append(body);parent.append(table,el('p',grid.assumptions));for(const row of grid.cases)parent.append(el('p',`${row.case}: ${row.rationale}`));parent.append(el('small',grid.qualification));
}
async function showReport(){const data=await get(`/api/runs/${selected}/report`);const signature=JSON.stringify(data);if(signature===previousReport)return;previousReport=signature;const {job,product,publication}=data;
 const header=$('reportHeader');header.replaceChildren(badge(job.status),el('h1',job.scope.join(' · ')+' — overall assessment'),el('p',job.question,'report-brief'),el('p',`${job.scope.join(' · ')} / ${(job.horizon_sessions||[63]).join(' / ')} trading sessions · Started ${date(job.created_at)}${publication?' · Published '+date(publication.published_at):''}`));
 const actions=$('reportActions');actions.replaceChildren(link('Open run monitor',`/monitor?run=${job.id}`,'button secondary'));const save=el('button','Download report JSON','secondary');save.onclick=()=>download(data,`${job.id}-report.json`);actions.append(save);
 ResearchReport.agents($('agentReports'),data.agent_reports||[],`/api/runs/${job.id}`,()=>{location.href=`/monitor?run=${job.id}`;},data.charts||[]);
 $('reportCharts').replaceChildren();ResearchReport.charts($('reportCharts'),data.charts||[],`/api/runs/${job.id}`);
 const overview=$('conclusion');overview.replaceChildren();$('instruments').replaceChildren();$('supporting').replaceChildren();
 if(job.error||job.stop_reason)overview.append(el('p',job.error||job.stop_reason,'empty'));
 if(data.delivery_check?.status==='BLOCKED'){overview.append(el('h2','Research incomplete'),el('p','Required analysis was not delivered.'));for(const gap of data.delivery_check.missing)overview.append(el('p',gap));}
 if(!product){readinessTable(overview,data.source_readiness);overview.append(el('p',job.busy?'Research is in progress. Accepted specialist findings are available in the monitor; final conclusions will appear here.':`No final report is available. Saved status: ${job.status}. Inspect the monitor for partial findings and the stop reason.`,'empty'));return;}
 if(!publication){const note=el('div',undefined,'overview');note.append(el('h2','Draft conclusions'),el('p',product.as_of_record?'Assessment and source times are recorded below. This saved draft is unpublished; review the conclusions and limits before a separate publication refresh.':'This saved draft is unpublished and awaits publication refresh. Review the evidence and limitations.'));overview.append(note);
   if(job.status==='DRAFT'&&!job.publication_attempted&&!job.saved_evaluation&&!job.busy){const b=el('button','Reviewed — refresh & publish');b.onclick=async()=>{b.disabled=true;try{await post(`/api/runs/${job.id}/publish`,{reviewed:true});$('notice').textContent='Publication refresh started. Material changes may withdraw affected conclusions.';previousReport=null;}catch(e){$('notice').textContent=String(e);b.disabled=false;}};actions.append(b);}}
 else{const note=el('div',undefined,'overview');note.append(el('h2','Published research'),el('p',`Immutable publication ${publication.publication_id}. Evidence cutoff: ${date(product.evidence_cutoff)}.`),el('p',`Price freshness: ${product.price_freshness?.status||'see freshness record'}. Executable quote: ${product.quote_freshness?.status||'unavailable'}.`));overview.append(note);}
 if(product.as_of_record){const clock=product.as_of_record,note=el('section',undefined,'time-context');note.append(el('h2',`As of ${date(clock.assessed_at)}`),el('p',`Market ${clock.market.status.toLowerCase()} · Last completed session ${clock.market.latest_completed_session} · Requested ${date(clock.requested_at)}`));for(const stock of clock.stocks){const row=el('div',undefined,'price-observation');row.append(el('strong',stock.symbol));if(stock.completed_close)row.append(el('span',`Completed close: $${Number(stock.completed_close.price).toFixed(2)} on ${stock.completed_close.date}`));const trade=stock.snapshot?.latest_trade;if(trade)row.append(el('small',`Last ${stock.snapshot.feed.toUpperCase()} trade: $${Number(trade.price).toFixed(2)} at ${date(trade.observed_at)}`));row.append(el('small',`Quote: ${label(stock.quote_status)} · Captured ${date(stock.captured_at)}`));note.append(row);}note.append(el('small',clock.qualification));overview.append(note);}
 const summary=el('div',undefined,'overview');summary.append(el('h2','Overall assessment'),el('p',product.findings.summary));overview.append(summary);
 for(const row of product.findings.instruments||[]){
  const card=el('article',undefined,'instrument');card.append(el('h2',row.symbol),badge(row.assessment));
  if(row.dimensions)card.append(el('small','Relative assessment'));
  textSection(card,'Overall view',row.global_analysis?.overall_assessment||row.thesis);
  textSection(card,'Opposing case',row.counter_thesis);
  if(row.global_analysis){const a=row.global_analysis,forces=el('details');forces.append(el('summary','Global forces that matter'));for(const force of a.global_forces){forces.append(el('h3',force.force),el('p',force.mechanism),el('p','Consequence: '+force.consequence));for(const id of force.evidence_ids||[])forces.append(link(`Evidence ${id.slice(0,10)} ↗`,`/api/runs/${job.id}/artifact/evidence/${id}`));}card.append(forces);card.append(el('h3','Plausible conditional outcomes'));for(const outcome of a.conditional_outcomes){const d=el('details',undefined,'outcome');d.append(el('summary',label(outcome.case)+' case'),el('p','If: '+outcome.condition),el('p','Then: '+outcome.consequence),el('small','Plausibility basis: '+outcome.plausibility_basis));for(const id of outcome.evidence_ids||[])d.append(link(`Evidence ${id.slice(0,10)} ↗`,`/api/runs/${job.id}/artifact/evidence/${id}`));card.append(d);}textSection(card,'What I recommend considering',a.recommend_considering);}
  const detail=el('details');detail.append(el('summary','Drivers, valuation & assumptions'));
  if(row.dimensions)dimensionSections(detail,row.dimensions);else textSection(detail,'Valuation assumptions',row.valuation);
  for(const grid of data.scenario_grids||[])if(grid.symbol===row.symbol){const scenarios=el('details');scenarios.append(el('summary','Bear / base / bull valuation table'));scenarioTable(scenarios,grid);detail.append(scenarios);}
  if(row.assumptions?.length){detail.append(el('h3','Assumptions'));for(const assumption of row.assumptions)detail.append(el('p',assumption));}
  if(row.etf_lookthrough)textSection(detail,'ETF exposure',row.etf_lookthrough);card.append(detail);
  card.append(el('h3','What would change this assessment'));conditions(card,row.review_conditions);
  const claims=(product.findings.claims||[]).filter(c=>(row.claim_ids||[]).includes(c.claim_id));const proof=el('details');proof.append(el('summary',`Supporting claims (${claims.length})`));
  for(const claim of claims){proof.append(el('p',`${label(claim.classification)}: ${claim.text}`));for(const id of claim.evidence_ids||[])proof.append(link(`Evidence ${id.slice(0,10)} ↗`,`/api/runs/${job.id}/artifact/evidence/${id}`),el('br'));}card.append(proof);$('instruments').append(card);
 }
 const support=$('supporting');readinessTable(support,data.source_readiness);for(const key of ['gaps','shared_exposures'])if(product.findings[key]?.length){const d=el('details');d.append(el('summary',label(key)));for(const row of product.findings[key])d.append(el('p',typeof row==='string'?row:row.description||row.explanation||row.text||JSON.stringify(row)));support.append(d);}for(const key of ['question_effects','objection_dispositions','role_coverage'])if(product.findings[key]?.length)disclosure(support,'Saved '+label(key),product.findings[key]);
 const limitations=el('section');limitations.append(el('h2','Limitations'));const ul=el('ul');for(const text of product.limitations||[])ul.append(el('li',text));limitations.append(ul);support.append(limitations);
 const sources=el('details');sources.append(el('summary',`Evidence & source dates (${data.sources.length})`));for(const source of data.sources){const row=el('div',undefined,'source');row.append(link(source.title||source.source_id||source.evidence_id,`/api/runs/${job.id}/artifact/evidence/${source.evidence_id}`));if(source.url&&/^https:\/\//.test(source.url)){const a=link(' · Original source ↗',source.url);a.target='_blank';a.rel='noopener noreferrer';row.append(a);}row.append(el('small',`Observed: ${source.observed_dates?.join(', ')||source.data?.price_date||source.data?.as_of||source.published_at||'not recorded'} · Retrieved: ${date(source.retrieved_at)}`));sources.append(row);}support.append(sources);if(publication)disclosure(support,'Publication refresh, conditions & freshness',{refresh:publication.refresh,price_freshness:product.price_freshness,quote_freshness:product.quote_freshness});
}
async function refresh(){try{workspace=await get('/api/workspace');if(selected){await showReport();}else{list($('recent'),workspace.jobs.slice(0,3));list($('library'),workspace.jobs);$('start').disabled=submitting||workspace.jobs.some(j=>j.busy);}}catch(e){$('notice').textContent=`Connection or saved-record error: ${e}. Previously displayed results may be outdated.`;}}
$('researchForm').onsubmit=async event=>{event.preventDefault();if(submitting)return;submitting=true;$('start').disabled=true;const question=$('question').value.trim(),symbols=$('symbols').value.split(/[\s,]+/).filter(Boolean).map(s=>s.toUpperCase()),horizon_sessions=[...document.querySelectorAll('[name=horizon]:checked')].map(n=>Number(n.value));const input=JSON.stringify({question,symbols,horizon_sessions});if(pendingQuestion!==null&&pendingQuestion!==input)requestId=crypto.randomUUID();pendingQuestion=input;try{if(!horizon_sessions.length)throw Error('Choose at least one time horizon');const job=await post('/api/runs',{id:requestId,question,symbols,horizon_sessions});location.href=`/reports?run=${job.id}`;}catch(e){$('notice').textContent=`${e}. The same unchanged submission keeps its request ID, so retrying does not duplicate a run.`;submitting=false;$('start').disabled=false;}};
(async()=>{try{workspace=await get('/api/workspace');$('question').value=workspace.question;const b=workspace.budgets;$('budget').textContent=`Up to ${b.model_calls} calls · ${Math.round(b.wall_seconds/60)} minutes · $${b.catalog_cost_usd} catalog estimate ceiling`;$('model').textContent=`Model: ${workspace.model}`;const library=location.pathname==='/reports';$(selected?'detail':library?'reports':'entry').hidden=false;$(library?'reportsNav':'newNav').setAttribute('aria-current','page');await refresh();setInterval(refresh,3000);}catch(e){$('notice').textContent=String(e);}})();

for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{for(const other of document.querySelectorAll('[data-view]'))other.setAttribute('aria-pressed',String(other===b));for(const name of ['overview','agents','evidence'])$(name+'View').hidden=name!==b.dataset.view;};
